apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ziralink-api.fullname" . }}
data:
  ASPNETCORE_ENVIRONMENT: "{{ .Values.environmentVariables.environment }}"
  ZIRALINK_CONNECTIONSTRINGS_DB: "{{ .Values.environmentVariables.connectionStrings.db }}"
  ZIRALINK_CONNECTIONSTRINGS_REDIS: "{{ .Values.environmentVariables.connectionStrings.redis }}"
  ZIRALINK_URL_IDS: "{{ .Values.environmentVariables.idsUrl }}"
  ZIRALINK_REDIRECTURI: "{{ .Values.environmentVariables.idsRedirectUrl }}"
  ZIRALINK_WEB_URL: "{{ .Values.environmentVariables.webUrl }}"
  ASPNETCORE_URLS: "{{ .Values.environmentVariables.aspNetCoreUrls }}"
  ASPNETCORE_Kestrel__Certificates__Default__Password: "{{ .Values.environmentVariables.certificatePassword }}"
  ASPNETCORE_Kestrel__Certificates__Default__Path: "{{ .Values.environmentVariables.certificatePath }}"